// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkNmbafZ8biGoEykjIoPgz4JSvPVzaFyw',
    appId: '1:53318494705:web:2988620ab7b7d864ea7c50',
    messagingSenderId: '53318494705',
    projectId: 'project-eec0b',
    authDomain: 'project-eec0b.firebaseapp.com',
    storageBucket: 'project-eec0b.firebasestorage.app',
    measurementId: 'G-0MQ4VWYWE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbhKHwza4W7-nAWBN1NKJyZT7fNh8llv4',
    appId: '1:53318494705:android:f59954ecda2a359bea7c50',
    messagingSenderId: '53318494705',
    projectId: 'project-eec0b',
    storageBucket: 'project-eec0b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_wj92ZFpK5pv4ym0Cds9lZhaFiik4tJo',
    appId: '1:53318494705:ios:ff101eca24199eb7ea7c50',
    messagingSenderId: '53318494705',
    projectId: 'project-eec0b',
    storageBucket: 'project-eec0b.firebasestorage.app',
    androidClientId: '53318494705-ve797lj9daid1ll3rrlag7f4q9vokkr6.apps.googleusercontent.com',
    iosClientId: '53318494705-p11jbu4prgvmtareq7g2fk08cj8ila7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_wj92ZFpK5pv4ym0Cds9lZhaFiik4tJo',
    appId: '1:53318494705:ios:ff101eca24199eb7ea7c50',
    messagingSenderId: '53318494705',
    projectId: 'project-eec0b',
    storageBucket: 'project-eec0b.firebasestorage.app',
    androidClientId: '53318494705-ve797lj9daid1ll3rrlag7f4q9vokkr6.apps.googleusercontent.com',
    iosClientId: '53318494705-p11jbu4prgvmtareq7g2fk08cj8ila7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkNmbafZ8biGoEykjIoPgz4JSvPVzaFyw',
    appId: '1:53318494705:web:f03da4ff76319dc4ea7c50',
    messagingSenderId: '53318494705',
    projectId: 'project-eec0b',
    authDomain: 'project-eec0b.firebaseapp.com',
    storageBucket: 'project-eec0b.firebasestorage.app',
    measurementId: 'G-KTJWYBJDN9',
  );
}
